import 'package:todo_app/moduls/todo.dart';

List<Todo> todosDummy = [
  Todo(
    id: 1,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 2,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 3,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 4,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 5,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 6,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 7,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 8,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 9,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 10,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 11,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 12,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 13,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 14,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
  Todo(
    id: 15,
    categoryId: 1,
    title: 'Todo ',
    description: 'description',
    status: Status.active,
    priority: Priority.major,
  ),
];
